### ISSUE TITLE
Does not play video

### ISSUE THREAD

**Issue by Rombersoft** [majorsilence/MPlayerControl#13]
I've opened video file but it is not played. I've clicked play button but nothing changed.
Also I see in output:
```
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.
The gl2 video output driver has been renamed to -vo gl_tiled, but you really should be using -vo gl instead.
X11 error: BadValue (integer parameter out of range for operation)
[gl] Could not create GLX context!
Error opening/initializing the selected video_out (-vo) device.
```
Linux Mint 18.2

**Comment by majorsilence** [comment]
Try changing the back end in https://github.com/majorsilence/MPlayerControl/blob/master/LibMPlayerCommon/MplayerBackends.cs and https://github.com/majorsilence/MPlayerControl/blob/master/LibMPlayerCommon/MPlayer.cs#L214.

Change gl2 to gl_tiled.  Fix any compile errors.  Test to see if it works and if it does send a pull request.

As an alternative as the output suggests you can try using the gl backend with MplayerBackends.GL.

**Comment by Rombersoft** [comment]
Thanks I understood
