### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by LordCM** [majorsilence/MPlayerControl#15]
When disposing instance of LibMPlayerCommon.MPlayer, mplayer executable (i'm using it on Linux) is not being killed and remains in memory. After few rounds, memory gets full (lot of orphaned mplayer processes).
Quick and dirty fix was to copy content of finalizer (which you are disabling in Dispose()) directly into Dispose method thus killing executable while doing Dispose()
Problem found in git version, on master

**Comment by majorsilence** [comment]
Is this with the current 1.2.0 nuget package or in master?

**Comment by LordCM** [comment]
found the problem and solution:
1. don't rely on user calling MPlayer.Quit()!
2. change cleanup/disposing. Either don't do "GC.SuppressFinalize(this);" on MPlayer instace when disposing, or call MediaPlayer.Kill() inside Dispose(true), otherwise there is a chance, that mplayer process will remain running and will become orphaned << this is happening to me

Currently i have changed your code like this:

        ~MPlayer()
        {
            Dispose(false);
        }


        public void Dispose()
        { 
            Dispose(true);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposed)
                return; 

            if (disposing)
            {
                if (MediaPlayer != null)
                {
                    try
                    {
                        if (MediaPlayer.HasExited == false)
                            MediaPlayer.Kill();
                    }
                    catch (Exception ex)
                    {
                        Logging.Instance.WriteLine(ex);
                    }
                    MediaPlayer.Dispose();
                    MediaPlayer = null;
                }
            }
                
            disposed = true;
        }


FYI: i'm using git version of your library on Ubuntu Mate running on Raspberry Pi 3

**Comment by majorsilence** [comment]
Do you want to send a pull request with the fix or just want me to copy and paste in your above fix?

I'm using ubuntu 16.04 with mono 5.10 and have been unable to reproduce this issue.  What version of mono are you using?

**Comment by LordCM** [comment]
i'm using latest version of mono.
bug does not happen all the time. im playing short videos (5-15 sec) in a loop, and after about 8 hours of playback, i have more than 10 orphaned mplayer proceses, each using more than 100mb mem. on RPi, where you have only about 700mb mem, this is serious problem.
if you are ok with my fix, please add it to your repo.
