### ISSUE TITLE
Where is WpfMPlayer?

### ISSUE THREAD

**Issue by mysteryx93** [majorsilence/MPlayerControl#16]
To use in a WPF application, it says: Add a reference to LibMPlayerCommon, LibImages, and WpfMPlayer

There is no LibImages nor WpfMPlayer in NuGet. Where do I get those libraries?

**Comment by majorsilence** [comment]
LibImages is part of the MplayerControl nuget package.  It appears there is no wpfmplayer package published.  This is a bug and should be included in the next release.

**Comment by mysteryx93** [comment]
When is next release?

**Comment by mysteryx93** [comment]
After looking at the code, considering the WPF (and WinForms) implementation is a very simple class, poorly structured, with a bad UI, and that it doesn't even expose any player properties(!), it's probably best to simply reference the Common class and copy the Wpf class into my own project to implement it based on my needs.
