### ISSUE TITLE
Video popping up in new window? 

### ISSUE THREAD

**Issue by Hakonvl** [majorsilence/MPlayerControl#17]
Hello!

This is a question about how this software is supposed to work, rather than a bug report.

When using the gtk-widget, should the video play inside the gtk window, or should mplayer start in a separate window, as it does for me? Using Ubuntu 18.04 with supplied mono and gtk from nuget.

I'm having problems problems building from git, so I'm just asking before spending much time on fixing something that might not really be broken. Thanks.

**Comment by majorsilence** [comment]
Fixed in
