### ISSUE TITLE
fix this in doc

### ISSUE THREAD

**Issue by jamesjeck** [majorsilence/MPlayerControl#18]
https://github.com/majorsilence/MPlayerControl/wiki/Create-X264-Video

a.ConversionComplete += New LibMPlayerCommon.MplayerEventHandler(AddressOf a_ConversionComplete)

        AddHandler a.ConversionComplete, New LibMPlayerCommon.MplayerEventHandler(AddressOf a_ConversionComplete)

**Comment by majorsilence** [comment]
K, thanks.  Done.
