### ISSUE TITLE
Gtk Sharp control doesn't work -- here is a fix

### ISSUE THREAD

**Issue by sonicmouse** [majorsilence/MPlayerControl#20]
This is for Linux specifically:

In the control, you are pulling the WID param from drawable.Handle. The handle that returns is an internal handle that's not related to an X11 ID which mplayer needs.

In order to get this ID, we first need the Drawable object, which you can get using this method:

`MyTargetWindow.GdkWindow.GetInternalPaintInfo(out var realDrawable, out var x, out var y);`

We need to define a way to translate this drawable to the X11 ID, so define this:
```
[DllImport("gdk-x11-2.0", EntryPoint = "gdk_x11_drawable_get_xid")]
[return: MarshalAs(UnmanagedType.U8)]
public static extern ulong GdkX11DrawableGetXID(IntPtr drawable);
```
Then you can call it as so:
`var x11id = GdkX11DrawableGetXID(realDrawable.Handle);`

The value in `x11id` is what you'd pass in the WID parameter:
`Arguments = $"-quiet -v -ontop -slave -idle -vo x11 -wid {x11id}"`

Also, you have to use the X11 backend. In MPlayer's documentation, the `-vo` option only works with X11, OpenGL and DirectX.

Source code in question: https://github.com/majorsilence/MPlayerControl/blob/master/MPlayerGtkWidget/GtkMPlayerWidget.cs

**Comment by sonicmouse** [comment]
This is for Windows specifically:

```
[DllImport("libgdk-win32-2.0-0.dll", EntryPoint = "gdk_win32_drawable_get_handle", CallingConvention = CallingConvention.Cdecl)]
public static extern IntPtr GdkWindowToWin32Window(IntPtr raw);
```
Then call it as so:

```
var hWnd = GdkWindowToWin32Window(realDrawable.Handle);
Arguments = $"-quiet -v -ontop -slave -idle -vo directx -wid {hWnd}"
```

**Comment by majorsilence** [comment]
@sonicmouse I checked on this last night.  I don't seem to be able to even compile the gtk project anymore, at least on ubuntu 18.04, as it says gtk sharp is missing even when it is installed.  Could you send a pull request with your changes?

I'm thinking I'll just do a new gtk widget based on gtk 3 at some point.

**Comment by Krutonium** [comment]
I'm in the same situation, it won't compile - I think it's because it's expecting an older version of GTKSharp than is available?

**Comment by majorsilence** [comment]
If I get a chance this weekend I might look into using https://www.nuget.org/packages/GtkSharp/ and creating a gtk 3 example widget.

**Comment by sonicmouse** [comment]
hey sorry for the delay -- been busy with other things and haven't checked my email in a while.

As far as I know, mono only supports GTK 2. My examples only support 2.0, hence the `gdk-x11-2.0` library name.

When I install Mono on linux, i use the mono-complete installation which should install GTK 2.0. If it's not there, try following [these instructions](https://superuser.com/questions/605539/ubuntu-monodevelop-not-starting-gtk-sharp-missing).

I will find time to do a pull request with my changes. Just bear with me. If you can figure it out, by all means, go ahead and do it.

**Comment by majorsilence** [comment]
I see why I seem to be having so many problems with gtk.  When I ran everything through https://github.com/hvanbakel/CsprojToVs2017 it broke the gtk projects.

https://github.com/majorsilence/MPlayerControl/commit/02c8e512e9a76d08d6e91daa1cafb86de34369cb#diff-f23ebb8f5b2004f635704f739526ee74

When I revert that it picks up the gtk references and mostly builds but I still have one other problem that comes back, at least using rider on ubuntu 20.04.

I suspect I should be able to get it running this weekend and apply your patches.

**Comment by sonicmouse** [comment]
I can't push my branch up .. getting a 403, I am sure it's a permissions thing that I just don't have time to troubleshoot. So, to make things simple, I made the changes in one file. You can refactor as you deem necessary. The only thing I changed is I used `long` instead of `ulong`. Techincally, a window handle/window ID will never be negative, so the `MPlayer` control should take a `ulong` in it's constructor. But, it should be fine as-is.

Just so you guys know I'm not nuts, here is a picture of the code working:
![image](https://user-images.githubusercontent.com/2473180/79628573-a880f800-8107-11ea-9f28-11351261ec8f.png)

And here are my changes:
```

using System;
using System.Runtime.InteropServices;
using LibMPlayerCommon;


namespace MPlayerGtkWidget
{
	static class LinuxNative
	{
		[DllImport("gdk-x11-2.0",
			EntryPoint = "gdk_x11_drawable_get_xid")]
		[return: MarshalAs(UnmanagedType.I8)]
		public static extern long GdkX11DrawableGetXID(IntPtr drawable);
	}

	static class WindowsNative
	{
		[DllImport("libgdk-win32-2.0-0.dll",
			EntryPoint = "gdk_win32_drawable_get_handle",
			CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr GdkWindowToWin32Window(IntPtr raw);
	}

	[System.ComponentModel.ToolboxItem(true)]
	public partial class GtkMPlayerWidget : Gtk.Bin
	{
		MPlayer _play;

		public GtkMPlayerWidget()
		{
			this.Build();
		}

		private static long GetNativeWidgetHandle(Gtk.Widget widget)
		{
			var platform = Environment.OSVersion.Platform;
			if (PlatformID.Unix == platform)
			{
				widget.GdkWindow.GetInternalPaintInfo(
					out var realDrawable, out var x, out var y);
				return LinuxNative.GdkX11DrawableGetXID(realDrawable.Handle);
			}

			if (PlatformID.Win32NT == platform)
			{
				var hWnd = WindowsNative.GdkWindowToWin32Window(widget.Handle);
				return hWnd.ToInt64();
			}

			throw new PlatformNotSupportedException(
					"Only tested on Windows and Linux");
		}

		protected void OnButtonPlayClicked(object sender, System.EventArgs e)
		{
			if (_play != null)
			{
				_play.Stop();
			}

			if (System.IO.File.Exists(VideoPath) == false && VideoPath.StartsWith("http") == false)
			{
				throw new System.IO.FileNotFoundException("File not found", VideoPath);
			}

			var handle = GetNativeWidgetHandle(drawingareaVideo);

			_play = new MPlayer(handle, MplayerBackends.GL, MPlayerPath);
			_play.Play(VideoPath);
		}

		protected void OnButtonStopClicked(object sender, System.EventArgs e)
		{
			if (_play != null)
			{
				_play.Stop();
			}
		}

		public string MPlayerPath { get; set; }
		public string VideoPath { get; set; }
	}
}

```

**Comment by majorsilence** [comment]
Thanks.  I had a horrible time this weekend trying to get this working on ubuntu 20.04.  I don't know if it is something on my machine or rider or what.  In the end, I got it to compile but complaining that gdk-x11-2.0 does not exist.

I'll take another look at it when I get a chance.  I'll probably just merge it in as is.

**Comment by majorsilence** [comment]
@sonicmouse I've finally had a chance to really sit down and test this.  My problem was on my ubuntu 20.04 machine I had to change the following

```cs
[DllImport("gdk-x11-2.0",
			EntryPoint = "gdk_x11_drawable_get_xid")]
```

to be

```cs
[DllImport("libgdk-x11-2.0",
			EntryPoint = "gdk_x11_drawable_get_xid")]
```

I've merged the change it with you as the author.
