### ISSUE TITLE
Getting Full Path of Current Media File

### ISSUE THREAD

**Issue by izlence** [majorsilence/MPlayerControl#21]
I am able to  use mplayer.GetfileName() but it gives me only filename not full path.
When I checked the code, I noticed that there is another variable holding the full path 

> private` string currentFilePath;

in https://github.com/majorsilence/MPlayerControl/blob/master/LibMPlayerCommon/MPlayer.cs#L47

But since it's private, it cannot be accessible. 

Is there any way to get the full path of the current media file?
Thanks.

**Comment by majorsilence** [comment]
In the 1.6.0 nuget package there is now a readonly property CurrentFilePath that you can call to get the current playing file with full path.
