### ISSUE TITLE
WinForms Error when playing, following example

### ISSUE THREAD

**Issue by brightertools** [majorsilence/MPlayerControl#22]
## Summary

Error pressing Play button on winforms example

## Description

I have followed the example for winforms, the player control is loaded, but then get an error when pressing play.
"Object reference not set to an instance of an object."
There is no inner exception and no other details.

## Steps to Reproduce (for bugs)
1. Create a basic winforms app:
2. Reference Nuget Package:Install-Package MPlayerControl-Winform
3 Also added: Install-Package MPlayerControl
4. add code to button

```
LibMPlayerWinform.WinFormMPlayerControl playerControl = new LibMPlayerWinform.WinFormMPlayerControl();
            playerControl.Left = 0;
            playerControl.Top = 0;
            playerControl.Width = 200;
            playerControl.Height = 200;
            playerControl.MPlayerPath = @"MediaPlayer.exe";
            playerControl.VideoPath = @"ScreenSoda1.mp4";
            this.Controls.Add(playerControl);
```

I have tried setting specific paths and outputing the exe and mp4 to the bin folder

## Expected Behavior
The video should play

## Current Behavior
Get an error message: "Object reference not set to an instance of an object."

## Possible Solution
Dont know

## Context
Just trying a basic example

## Your Environment
Visual Studio 2019
.Net Framework 4.7.2 (also tried 4.5)
Windows 10

## Additional Comments:
1) The example code references: MPlayer.exe, but the file MediaPlayer.exe is what actually exists.
2) The control does show on screen (with the Stop and Play buttons) but clicking a button causes the error
3) Ideas: 
- Is its possible to have properties on the control to show/hide the Start/Stop Buttons
- Methods to Start() / Stop() the video?

**Comment by brightertools** [comment]
Some more info...

I cloned the source, and noticed:
The MediaPlayer project is .Net Framework 4.8 and 
the LibMPlayerWinform project is .Net Framework 4.5

My intention is to run this on mono on raspberry pi, (although never used mono...or raspberry pi) but,
Can these bet the same, eg 4.5 and what is the highest version supported with Mono?

Hope this helps.

**Comment by majorsilence** [comment]
I'll see if I can try it tonight.  I'll use [rider](https://www.jetbrains.com/rider/) on ubuntu 20.04 with whatever is the latest version of mono and mplayer included with ubuntu.  If I get it working I'll test it on my raspberry pi 4 using raspbian.

**Comment by majorsilence** [comment]
I've updated the examples found on page https://github.com/majorsilence/MPlayerControl/wiki/Play-a-video-using-Winform-Control.

I've also modified your code above while testing; on ubuntu 20.04 it looks like this.   The following, with the paths set to what is on your machine should work.   You need to upgrade to the latest nuget packages that were just published a few minutes ago.

```cs
LibMPlayerWinform.WinFormMPlayerControl playerControl = new LibMPlayerWinform.WinFormMPlayerControl();

var player = LibMPlayerCommon.PlayerFactory.Get(playerControl.Handle, "/usr/bin/mplayer");
playerControl.SetPlayer(player);

playerControl.Left = 0;
playerControl.Top = 0;
playerControl.Width = 200;
playerControl.Height = 200;

playerControl.MPlayerPath = @"/usr/bin/mplayer";
playerControl.VideoPath = @"/home/peter/Downloads/20200717_183033.mp4";

this.Controls.Add(playerControl);
```

**Comment by brightertools** [comment]
Thanks for updating, I have tested this by using both your code to create `WinFormMPlayerControl` and the `Player` on the fly and by adding the control to the form and I get the error when I press the Play button:

`System.IO.InvalidDataException: 'The player is not set.  You must set it with the constructor or through the SetPlayer method.'`

Your examples reference 'mplayer.exe', whilst the 'MediaPlayer.exe' is available when referencing the nuget package? could this be different?

**Comment by brightertools** [comment]
I created a new application creating the form from the fly as per your example:

[https://github.com/brightertools/MPlayerControlExample](https://github.com/brightertools/MPlayerControlExample)

**Comment by majorsilence** [comment]
On windows you have to download an MPlayer package and point to its MPlayer.exe executable.

On linux such as ubuntu you have to install mplayer with apt install mplayer and point to mplayer such as /usr/bin/mplayer.

MediaPlayer.exe is just ab example winform app.

You also have to call the SetPlayer method.

**Comment by brightertools** [comment]
Thanks, will try that, do you have a link to the windows package?

**Comment by majorsilence** [comment]
I generally use

**Comment by brightertools** [comment]
Hi,

Thanks for the info and all your help.

I now have this running on windows,  however on Raspbian, its only running when I am logging in remotely via RDP (using xrdp) but not when I run the same app on the pi, with a touchscreen? This seems bizarre, any ideas on why this would be the case?

Observation:
The player has a Stop and Play button, which I have removed with:
```
VideoPlayer.Controls[0].Hide();
VideoPlayer.Controls[1].Hide();
```

This works, however the video doesn't use the whole height of the control (ie the space for the buttons)
It would be great to a) Have a method to hide the buttons and b) also hide the area the buttons are on, to use all the available space.
